//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthKIOSK.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long PatientId { get; set; }
        public Nullable<bool> Merged { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CountryId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SSN { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public Nullable<short> PreferredLanguageId { get; set; }
        public Nullable<short> GenderId { get; set; }
        public Nullable<short> RaceId { get; set; }
        public Nullable<short> EthnicityId { get; set; }
        public Nullable<short> MaritalStatusId { get; set; }
        public string AddressB1 { get; set; }
        public string AddressB2 { get; set; }
        public string AddressB3 { get; set; }
        public string CityB { get; set; }
        public string StateB { get; set; }
        public string ZipB { get; set; }
        public string CountryIdB { get; set; }
        public Nullable<bool> IsPregnant { get; set; }
        public Nullable<long> PatientId_Pregnancy { get; set; }
        public Nullable<long> Ncpdp_id { get; set; }
        public string ExternalId { get; set; }
        public Nullable<bool> Employed { get; set; }
        public Nullable<long> PharmacyId { get; set; }
        public Nullable<long> ProviderId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ProviderId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ProviderId_Deactivated { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public Nullable<long> PortalId { get; set; }
        public Nullable<bool> IncompleteRegistration { get; set; }
    }
}
